/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGCMCLIENT_AUTODEFS_H
#define S3EGCMCLIENT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GCMCLIENT_NAME "s3eGCMClient"
#define S3E_EXT_GCMCLIENT_HASH 0x70781a66

#endif /* !S3EGCMCLIENT_AUTODEFS_H */
